export const PERMISSIONS = {
  // User Management
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  // Role Management
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE', // Create, Update, Delete Roles & Permissions

  // Student Management
  STUDENT_VIEW: 'STUDENT_VIEW',
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',

  // Teacher & Staff Management
  TEACHER_VIEW: 'TEACHER_VIEW',
  TEACHER_MANAGE: 'TEACHER_MANAGE',
  STAFF_VIEW: 'STAFF_VIEW',
  STAFF_MANAGE: 'STAFF_MANAGE',

  // Academic / Curriculum
  ACADEMIC_VIEW: 'ACADEMIC_VIEW',
  ACADEMIC_MANAGE: 'ACADEMIC_MANAGE', // Subjects, Classes, Schedules

  // Exams & Grades
  EXAM_VIEW: 'EXAM_VIEW',
  EXAM_MANAGE: 'EXAM_MANAGE',
  GRADE_VIEW: 'GRADE_VIEW',
  GRADE_MANAGE: 'GRADE_MANAGE',

  // Finance
  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_MANAGE: 'FINANCE_MANAGE', // Invoices, Payments, Budgets

  // Inventory / Assets
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',

  // Library
  LIBRARY_VIEW: 'LIBRARY_VIEW',
  LIBRARY_MANAGE: 'LIBRARY_MANAGE',

  // Health / UKS
  HEALTH_VIEW: 'HEALTH_VIEW',
  HEALTH_MANAGE: 'HEALTH_MANAGE',

  // Dormitory / Pesantren
  DORMITORY_VIEW: 'DORMITORY_VIEW',
  DORMITORY_MANAGE: 'DORMITORY_MANAGE',

  // Tahfidz
  TAHFIDZ_VIEW: 'TAHFIDZ_VIEW',
  TAHFIDZ_MANAGE: 'TAHFIDZ_MANAGE',

  // Admissions (PSB)
  ADMISSION_VIEW: 'ADMISSION_VIEW',
  ADMISSION_MANAGE: 'ADMISSION_MANAGE',

  // Settings
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_GROUPS = {
  USER: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
  ],
  ROLE: [PERMISSIONS.ROLE_VIEW, PERMISSIONS.ROLE_MANAGE],
  STUDENT: [
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
  ],
  EMPLOYEE: [
    PERMISSIONS.TEACHER_VIEW,
    PERMISSIONS.TEACHER_MANAGE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_MANAGE,
  ],
  ACADEMIC: [
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ACADEMIC_MANAGE,
    PERMISSIONS.EXAM_VIEW,
    PERMISSIONS.EXAM_MANAGE,
    PERMISSIONS.GRADE_VIEW,
    PERMISSIONS.GRADE_MANAGE,
  ],
  FINANCE: [PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE],
  ASSETS: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE],
  LIBRARY: [PERMISSIONS.LIBRARY_VIEW, PERMISSIONS.LIBRARY_MANAGE],
  HEALTH: [PERMISSIONS.HEALTH_VIEW, PERMISSIONS.HEALTH_MANAGE],
  PESANTREN: [
    PERMISSIONS.DORMITORY_VIEW,
    PERMISSIONS.DORMITORY_MANAGE,
    PERMISSIONS.TAHFIDZ_VIEW,
    PERMISSIONS.TAHFIDZ_MANAGE,
  ],
  ADMISSION: [PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.ADMISSION_MANAGE],
  SYSTEM: [PERMISSIONS.SETTINGS_MANAGE],
};
