-- Expand roles & realms hierarchy (rebuilt additively from PR #319).
--
-- Adds: UNIT_USAHA realm/unit-type; granular per-school roles (wakasek,
-- wali kelas, guru BK, bendahara, komite, alumni); pesantren leadership and
-- gender-segregated pembina roles; Perguruan Tinggi additions; business-unit
-- roles. Enum ADD VALUE only — no tables touched, fully backward compatible.

-- Realm
ALTER TYPE "Realm" ADD VALUE IF NOT EXISTS 'UNIT_USAHA';

-- UnitType
ALTER TYPE "UnitType" ADD VALUE IF NOT EXISTS 'UNIT_USAHA';

-- RoleCode — TK Qur'an
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_WAKASEK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_WALI_KELAS';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_GURU_BK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_BENDAHARA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_KOMITE';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'TKQ_ALUMNI';

-- RoleCode — SD IT
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_WAKASEK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_WALI_KELAS';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_GURU_BK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_BENDAHARA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_KOMITE';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SDIT_ALUMNI';

-- RoleCode — SMP IT
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_WAKASEK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_WALI_KELAS';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_GURU_BK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_BENDAHARA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_KOMITE';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMPIT_ALUMNI';

-- RoleCode — SMA Qur'an
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_WAKASEK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_WALI_KELAS';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_GURU_BK';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_BENDAHARA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_KOMITE';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'SMAQ_ALUMNI';

-- RoleCode — Perguruan Tinggi additions
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PT_WAKIL_REKTOR';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PT_TATA_USAHA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PT_ALUMNI';

-- RoleCode — Pesantren leadership + gender-segregated pembina
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PESANTREN_PENGASUH';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PESANTREN_DIREKTUR';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PESANTREN_TATA_USAHA';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'USTADZ';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'MUSYRIFAH';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'MUHAFIDZAH';

-- RoleCode — Cross-unit support staff (library, UKS/clinic, security, labs)
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PUSTAKAWAN';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'PERAWAT';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'KEAMANAN';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'LABORAN';

-- RoleCode — Business units
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'BUSINESS_MANAGER';
ALTER TYPE "RoleCode" ADD VALUE IF NOT EXISTS 'BUSINESS_STAFF';
