export const PERMISSIONS = {
  // User Management
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  // Role Management
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Student Management
  STUDENT_VIEW: 'STUDENT_VIEW',
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',

  // Teacher & Staff Management
  TEACHER_VIEW: 'TEACHER_VIEW',
  TEACHER_MANAGE: 'TEACHER_MANAGE',
  STAFF_VIEW: 'STAFF_VIEW',
  STAFF_MANAGE: 'STAFF_MANAGE',

  // Academic
  ACADEMIC_VIEW: 'ACADEMIC_VIEW',
  ACADEMIC_MANAGE: 'ACADEMIC_MANAGE',

  // Exams & Grades
  EXAM_VIEW: 'EXAM_VIEW',
  EXAM_MANAGE: 'EXAM_MANAGE',
  GRADE_VIEW: 'GRADE_VIEW',
  GRADE_MANAGE: 'GRADE_MANAGE',

  // Finance
  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_MANAGE: 'FINANCE_MANAGE',

  // Inventory
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',

  // Library
  LIBRARY_VIEW: 'LIBRARY_VIEW',
  LIBRARY_MANAGE: 'LIBRARY_MANAGE',

  // Health
  HEALTH_VIEW: 'HEALTH_VIEW',
  HEALTH_MANAGE: 'HEALTH_MANAGE',

  // Pesantren
  DORMITORY_VIEW: 'DORMITORY_VIEW',
  DORMITORY_MANAGE: 'DORMITORY_MANAGE',
  TAHFIDZ_VIEW: 'TAHFIDZ_VIEW',
  TAHFIDZ_MANAGE: 'TAHFIDZ_MANAGE',

  // Admissions
  ADMISSION_VIEW: 'ADMISSION_VIEW',
  ADMISSION_MANAGE: 'ADMISSION_MANAGE',

  // Settings
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
} as const;

export const PERMISSION_GROUPS = {
  USER: [PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_DELETE],
  ROLE: [PERMISSIONS.ROLE_VIEW, PERMISSIONS.ROLE_MANAGE],
  STUDENT: [PERMISSIONS.STUDENT_VIEW, PERMISSIONS.STUDENT_CREATE, PERMISSIONS.STUDENT_UPDATE, PERMISSIONS.STUDENT_DELETE],
  EMPLOYEE: [PERMISSIONS.TEACHER_VIEW, PERMISSIONS.TEACHER_MANAGE, PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE],
  ACADEMIC: [PERMISSIONS.ACADEMIC_VIEW, PERMISSIONS.ACADEMIC_MANAGE, PERMISSIONS.EXAM_VIEW, PERMISSIONS.EXAM_MANAGE, PERMISSIONS.GRADE_VIEW, PERMISSIONS.GRADE_MANAGE],
  FINANCE: [PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE],
  ASSETS: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_MANAGE],
  LIBRARY: [PERMISSIONS.LIBRARY_VIEW, PERMISSIONS.LIBRARY_MANAGE],
  HEALTH: [PERMISSIONS.HEALTH_VIEW, PERMISSIONS.HEALTH_MANAGE],
  PESANTREN: [PERMISSIONS.DORMITORY_VIEW, PERMISSIONS.DORMITORY_MANAGE, PERMISSIONS.TAHFIDZ_VIEW, PERMISSIONS.TAHFIDZ_MANAGE],
  ADMISSION: [PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.ADMISSION_MANAGE],
  SYSTEM: [PERMISSIONS.SETTINGS_MANAGE],
};

export const PERMISSION_LABELS: Record<string, string> = {
  USER_VIEW: 'View Users',
  USER_CREATE: 'Create User',
  USER_UPDATE: 'Update User',
  USER_DELETE: 'Delete User',
  ROLE_VIEW: 'View Roles',
  ROLE_MANAGE: 'Manage Roles',
  STUDENT_VIEW: 'View Students',
  STUDENT_CREATE: 'Create Student',
  STUDENT_UPDATE: 'Update Student',
  STUDENT_DELETE: 'Delete Student',
  TEACHER_VIEW: 'View Teachers',
  TEACHER_MANAGE: 'Manage Teachers',
  STAFF_VIEW: 'View Staff',
  STAFF_MANAGE: 'Manage Staff',
  ACADEMIC_VIEW: 'View Academic Data',
  ACADEMIC_MANAGE: 'Manage Academic Data',
  EXAM_VIEW: 'View Exams',
  EXAM_MANAGE: 'Manage Exams',
  GRADE_VIEW: 'View Grades',
  GRADE_MANAGE: 'Manage Grades',
  FINANCE_VIEW: 'View Finance',
  FINANCE_MANAGE: 'Manage Finance',
  INVENTORY_VIEW: 'View Inventory',
  INVENTORY_MANAGE: 'Manage Inventory',
  LIBRARY_VIEW: 'View Library',
  LIBRARY_MANAGE: 'Manage Library',
  HEALTH_VIEW: 'View Health',
  HEALTH_MANAGE: 'Manage Health',
  DORMITORY_VIEW: 'View Dormitories',
  DORMITORY_MANAGE: 'Manage Dormitories',
  TAHFIDZ_VIEW: 'View Tahfidz',
  TAHFIDZ_MANAGE: 'Manage Tahfidz',
  ADMISSION_VIEW: 'View Admissions',
  ADMISSION_MANAGE: 'Manage Admissions',
  SETTINGS_MANAGE: 'Manage Settings',
};
